/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.agm.view;
import com.agm.model.paintingInfo;
import com.amg.util.validationUtil;
import java.awt.Color;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dell
 */
public class AGM extends javax.swing.JFrame {
    private List<paintingInfo> artItemList;
    private java.awt.CardLayout cardLayout;
    private final validationUtil validationUtil;
    private final Color errorColor = new Color(255, 51, 0);
    private final Color yellowColor = new Color(239, 192, 32);
    private final Color greenColor = new Color(35, 101, 51);

    /**
     * Creates new form AGM
     */
    public AGM() {
        initComponents();
        validationUtil = new validationUtil();
        initializeLayout(); // Set up CardLayout and add screens
        initializeData(); // Initialize student data and table
        startProgress(); 
        // Set up CardLayout and add screens
       // initializeData(); // Initialize student data and table
        //startProgress();
    }
     private void initializeData() {
        artItemList = new LinkedList<>();

        // Registering sample students
        registerStudent(new paintingInfo(11, "Starry night", "27/01/2024", "Watercolor", "9841489349", 53, "narnia","Paper", "100 X 100"));
        registerStudent(new paintingInfo(11, "Starry night", "27/01/2024", "Watercolor", "9841489349", 53, "narnia","Paper", "100 X 100"));
    }
    private void registerStudent(paintingInfo items) {
        artItemList.add(items);
        DefaultTableModel model = (DefaultTableModel) mntable.getModel();
        model.addRow(new Object[]{
            items.getArtId(), items.getName(), items.getAddress(), items.getContact(), items.getDate(), items.getFormatt()
                ,items.getPrice(), items.getMedium(),items.getSize()
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        lgusernametxt = new javax.swing.JTextField();
        lgUsername = new javax.swing.JLabel();
        lgPassword = new javax.swing.JLabel();
        lgUsernamError = new javax.swing.JLabel();
        lgPasswordError = new javax.swing.JLabel();
        lgpasswordtxt = new javax.swing.JPasswordField();
        lgbutton = new javax.swing.JButton();
        lgImg = new javax.swing.JLabel();
        mnPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        mnGallery = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mntable = new javax.swing.JTable();
        mnAboutus = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        mnaadmin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mnIDtxt = new javax.swing.JTextField();
        mnNametxt = new javax.swing.JTextField();
        mnMeduimtxt = new javax.swing.JComboBox<>();
        mnContacttxt = new javax.swing.JTextField();
        mnDatetxt = new javax.swing.JTextField();
        idError = new javax.swing.JLabel();
        mnFormattxt = new javax.swing.JComboBox<>();
        mnPricetxt = new javax.swing.JTextField();
        mnSizetxt = new javax.swing.JTextField();
        mnStudioAddresstxt = new javax.swing.JTextField();
        nameError = new javax.swing.JLabel();
        sizeError = new javax.swing.JLabel();
        contactError = new javax.swing.JLabel();
        addressError = new javax.swing.JLabel();
        priceError = new javax.swing.JLabel();
        dateError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mnUpdateButton = new javax.swing.JButton();
        mnDeleteButton = new javax.swing.JButton();
        mnAddButton = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        mnHome = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        mnHimg = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mnLogoutButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnLoaddingscreen = new javax.swing.JPanel();
        scLoaddingscreen = new javax.swing.JProgressBar();
        imgLS = new javax.swing.JLabel();

        loginPanel.setMaximumSize(new java.awt.Dimension(1000, 600));
        loginPanel.setMinimumSize(new java.awt.Dimension(1000, 600));
        loginPanel.setPreferredSize(new java.awt.Dimension(1000, 600));
        loginPanel.setLayout(null);

        lgusernametxt.setBackground(java.awt.SystemColor.controlHighlight);
        lgusernametxt.setText("p");
        lgusernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgusernametxtActionPerformed(evt);
            }
        });
        loginPanel.add(lgusernametxt);
        lgusernametxt.setBounds(690, 310, 240, 30);

        lgUsername.setText("username");
        loginPanel.add(lgUsername);
        lgUsername.setBounds(557, 320, 80, 16);

        lgPassword.setText("password");
        loginPanel.add(lgPassword);
        lgPassword.setBounds(560, 390, 90, 16);
        loginPanel.add(lgUsernamError);
        lgUsernamError.setBounds(690, 350, 240, 20);
        loginPanel.add(lgPasswordError);
        lgPasswordError.setBounds(680, 420, 220, 20);

        lgpasswordtxt.setBackground(java.awt.SystemColor.controlHighlight);
        lgpasswordtxt.setText("z");
        lgpasswordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgpasswordtxtActionPerformed(evt);
            }
        });
        loginPanel.add(lgpasswordtxt);
        lgpasswordtxt.setBounds(690, 380, 240, 30);

        lgbutton.setText("login");
        lgbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgbuttonActionPerformed(evt);
            }
        });
        loginPanel.add(lgbutton);
        lgbutton.setBounds(730, 450, 140, 50);

        lgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/agm/resources/Frame 1 (3).png"))); // NOI18N
        lgImg.setText("jLabel1");
        lgImg.setMaximumSize(new java.awt.Dimension(1000, 600));
        lgImg.setMinimumSize(new java.awt.Dimension(1000, 600));
        lgImg.setPreferredSize(new java.awt.Dimension(1000, 600));
        loginPanel.add(lgImg);
        lgImg.setBounds(0, 0, 1000, 600);

        mnPanel.setBackground(new java.awt.Color(255, 255, 204));
        mnPanel.setMaximumSize(new java.awt.Dimension(1000, 600));
        mnPanel.setMinimumSize(new java.awt.Dimension(1000, 600));
        mnPanel.setPreferredSize(new java.awt.Dimension(1000, 600));
        mnPanel.setLayout(null);

        jTabbedPane2.setDoubleBuffered(true);
        jTabbedPane2.setMaximumSize(new java.awt.Dimension(1000, 600));
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(1000, 600));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(1000, 600));

        mnGallery.setMaximumSize(new java.awt.Dimension(1000, 700));
        mnGallery.setMinimumSize(new java.awt.Dimension(1000, 700));
        mnGallery.setPreferredSize(new java.awt.Dimension(1000, 700));

        mntable.setBackground(new java.awt.Color(255, 204, 102));
        mntable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ArtID", "Artist Name", "Date", "Meduim", "Contact", "Price", "Studio Address", "Format ", "Size"
            }
        ));
        jScrollPane1.setViewportView(mntable);

        javax.swing.GroupLayout mnGalleryLayout = new javax.swing.GroupLayout(mnGallery);
        mnGallery.setLayout(mnGalleryLayout);
        mnGalleryLayout.setHorizontalGroup(
            mnGalleryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnGalleryLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        mnGalleryLayout.setVerticalGroup(
            mnGalleryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnGalleryLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("gallery", mnGallery);

        mnAboutus.setFocusTraversalPolicyProvider(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Mandala art gallery is located in the heart of kathmandu and is old of the oldest art gallery to be \nestablished in Nepal. ");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout mnAboutusLayout = new javax.swing.GroupLayout(mnAboutus);
        mnAboutus.setLayout(mnAboutusLayout);
        mnAboutusLayout.setHorizontalGroup(
            mnAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnAboutusLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );
        mnAboutusLayout.setVerticalGroup(
            mnAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnAboutusLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("about us", mnAboutus);

        mnaadmin.setBackground(new java.awt.Color(204, 204, 255));
        mnaadmin.setMaximumSize(new java.awt.Dimension(1000, 800));
        mnaadmin.setMinimumSize(new java.awt.Dimension(1000, 800));
        mnaadmin.setPreferredSize(new java.awt.Dimension(1000, 800));
        mnaadmin.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        mnIDtxt.setBackground(new java.awt.Color(204, 204, 204));
        mnIDtxt.setBorder(null);
        mnIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIDtxtActionPerformed(evt);
            }
        });
        jPanel1.add(mnIDtxt);
        mnIDtxt.setBounds(110, 30, 210, 50);

        mnNametxt.setBorder(null);
        mnNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNametxtActionPerformed(evt);
            }
        });
        jPanel1.add(mnNametxt);
        mnNametxt.setBounds(110, 120, 210, 50);

        mnMeduimtxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acrylic", "Watercolor", "Oil", "Charcoal" }));
        mnMeduimtxt.setToolTipText("");
        mnMeduimtxt.setBorder(null);
        jPanel1.add(mnMeduimtxt);
        mnMeduimtxt.setBounds(460, 290, 210, 60);

        mnContacttxt.setText("98");
        mnContacttxt.setBorder(null);
        mnContacttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnContacttxtActionPerformed(evt);
            }
        });
        jPanel1.add(mnContacttxt);
        mnContacttxt.setBounds(110, 300, 210, 50);

        mnDatetxt.setText("dd/mm/yyyy");
        mnDatetxt.setBorder(null);
        mnDatetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDatetxtActionPerformed(evt);
            }
        });
        jPanel1.add(mnDatetxt);
        mnDatetxt.setBounds(110, 210, 210, 50);
        jPanel1.add(idError);
        idError.setBounds(109, 80, 210, 30);

        mnFormattxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paper", "Cloth", "Glass" }));
        mnFormattxt.setBorder(null);
        mnFormattxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFormattxtActionPerformed(evt);
            }
        });
        jPanel1.add(mnFormattxt);
        mnFormattxt.setBounds(110, 390, 190, 70);

        mnPricetxt.setBorder(null);
        mnPricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPricetxtActionPerformed(evt);
            }
        });
        jPanel1.add(mnPricetxt);
        mnPricetxt.setBounds(460, 110, 190, 50);

        mnSizetxt.setBorder(null);
        mnSizetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSizetxtActionPerformed(evt);
            }
        });
        jPanel1.add(mnSizetxt);
        mnSizetxt.setBounds(460, 210, 190, 50);

        mnStudioAddresstxt.setBorder(null);
        mnStudioAddresstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnStudioAddresstxtActionPerformed(evt);
            }
        });
        jPanel1.add(mnStudioAddresstxt);
        mnStudioAddresstxt.setBounds(460, 30, 190, 50);
        jPanel1.add(nameError);
        nameError.setBounds(110, 170, 210, 30);
        jPanel1.add(sizeError);
        sizeError.setBounds(460, 260, 190, 30);
        jPanel1.add(contactError);
        contactError.setBounds(110, 350, 210, 30);
        jPanel1.add(addressError);
        addressError.setBounds(460, 80, 190, 30);
        jPanel1.add(priceError);
        priceError.setBounds(460, 160, 190, 30);
        jPanel1.add(dateError);
        dateError.setBounds(110, 260, 210, 30);

        jLabel1.setText("id");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 70, 50);

        jLabel3.setText("name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 60, 50);

        jLabel4.setText("date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 210, 70, 50);

        jLabel5.setText("Meduim");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 290, 70, 60);

        jLabel6.setText("contact");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 300, 70, 50);

        jLabel7.setText("format");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 400, 80, 40);

        jLabel8.setText("price");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 110, 80, 50);

        jLabel9.setText("size");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(370, 220, 80, 30);

        jLabel10.setText("Address");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 30, 90, 50);

        mnaadmin.add(jPanel1);
        jPanel1.setBounds(20, 0, 770, 550);

        mnUpdateButton.setText("Update");
        mnUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUpdateButtonActionPerformed(evt);
            }
        });
        mnaadmin.add(mnUpdateButton);
        mnUpdateButton.setBounds(780, 40, 140, 55);

        mnDeleteButton.setText("delete");
        mnDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDeleteButtonActionPerformed(evt);
            }
        });
        mnaadmin.add(mnDeleteButton);
        mnDeleteButton.setBounds(780, 140, 140, 50);

        mnAddButton.setText("Add");
        mnAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAddButtonActionPerformed(evt);
            }
        });
        mnaadmin.add(mnAddButton);
        mnAddButton.setBounds(790, 220, 130, 50);

        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        mnaadmin.add(clear);
        clear.setBounds(800, 320, 130, 50);

        jTabbedPane2.addTab("admin", mnaadmin);

        mnHome.setBackground(new java.awt.Color(239, 239, 235));
        mnHome.setMaximumSize(new java.awt.Dimension(1000, 500));
        mnHome.setMinimumSize(new java.awt.Dimension(1000, 500));
        mnHome.setPreferredSize(new java.awt.Dimension(1000, 500));
        mnHome.setLayout(null);
        mnHome.add(jScrollPane4);
        jScrollPane4.setBounds(980, 0, 20, 340);

        mnHimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/agm/resources/image.png"))); // NOI18N
        mnHimg.setText("jLabel13");
        mnHome.add(mnHimg);
        mnHimg.setBounds(0, 0, 1047, 180);

        jLabel14.setFont(new java.awt.Font("Sitka Banner", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(54, 54, 51));
        jLabel14.setText("Welcome");
        mnHome.add(jLabel14);
        jLabel14.setBounds(30, 160, 870, 120);

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel2.setText("Curate with Curator's Best Friend!");
        mnHome.add(jLabel2);
        jLabel2.setBounds(40, 330, 790, 40);

        mnLogoutButton.setBackground(new java.awt.Color(255, 0, 0));
        mnLogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mnLogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        mnLogoutButton.setText("back");
        mnLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutButtonActionPerformed(evt);
            }
        });
        mnHome.add(mnLogoutButton);
        mnLogoutButton.setBounds(770, 200, 118, 30);

        jLabel11.setFont(new java.awt.Font("DialogInput", 0, 30)); // NOI18N
        jLabel11.setText("With functions like add update and delete,");
        mnHome.add(jLabel11);
        jLabel11.setBounds(20, 460, 940, 30);

        jLabel18.setFont(new java.awt.Font("DialogInput", 0, 30)); // NOI18N
        jLabel18.setText("art works effectively and efficiently.  ");
        mnHome.add(jLabel18);
        jLabel18.setBounds(20, 430, 940, 30);

        jLabel19.setFont(new java.awt.Font("DialogInput", 0, 30)); // NOI18N
        jLabel19.setText("This admin Panel is designed to help or manage the");
        mnHome.add(jLabel19);
        jLabel19.setBounds(20, 390, 940, 40);

        jLabel20.setFont(new java.awt.Font("DialogInput", 0, 30)); // NOI18N
        jLabel20.setText("you can easily manage the paintings with ease.");
        mnHome.add(jLabel20);
        jLabel20.setBounds(30, 490, 940, 30);

        jLabel15.setFont(new java.awt.Font("Sitka Banner", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(54, 54, 51));
        jLabel15.setText("Mandala Art Point Admin Panel");
        mnHome.add(jLabel15);
        jLabel15.setBounds(30, 200, 870, 120);

        jTabbedPane2.addTab("home", mnHome);

        mnPanel.add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 0, 1000, 600);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        pnLoaddingscreen.setLayout(null);

        scLoaddingscreen.setBackground(new java.awt.Color(255, 204, 102));
        pnLoaddingscreen.add(scLoaddingscreen);
        scLoaddingscreen.setBounds(370, 470, 280, 24);

        imgLS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/agm/resources/Frame 1 (1).png"))); // NOI18N
        imgLS.setText("jLabel1");
        imgLS.setMaximumSize(new java.awt.Dimension(1000, 600));
        imgLS.setMinimumSize(new java.awt.Dimension(1000, 600));
        imgLS.setPreferredSize(new java.awt.Dimension(1000, 600));
        imgLS.setRequestFocusEnabled(false);
        pnLoaddingscreen.add(imgLS);
        imgLS.setBounds(0, 0, 1000, 600);

        getContentPane().add(pnLoaddingscreen);
        pnLoaddingscreen.setBounds(0, 0, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(loginPanel, "LoginScreen");
        getContentPane().add(mnPanel, "MainScreen");
        getContentPane().add(pnLoaddingscreen, "LoadingScreen");

        // Start with the loading screen
        loadScreen("LoadingScreen");
    }
    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i); // Publish progress
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                scLoaddingscreen.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("LoginScreen"); // Switch to login screen
            }
        };
        worker.execute(); // Start the worker thread
    }
    
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    
    private void lgusernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgusernametxtActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        // Get the username and password input


    }//GEN-LAST:event_lgusernametxtActionPerformed
     
    private void lgpasswordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgpasswordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lgpasswordtxtActionPerformed

    private void lgbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgbuttonActionPerformed
        // TODO add your handling code here:
        String username = lgusernametxt.getText();
        String password = new String(lgpasswordtxt.getPassword());

        // Check if username is empty  
        if (username.isEmpty()) {
            lgUsernamError.setText("Please enter your username");
        }
        // Check if password is empty
        else if(password.isEmpty()){
            lgPasswordError.setText("Please enter your password.");
        }
         
        //Check if username and password are incorrect
        else if (!username.equals("p")) {
            lgUsernamError.setText("Username incorrect");
        } 
        
        //check if password is incorrect
        else if (!password.equals("z")) {
            lgPasswordError.setText("password incorrect.");
        } 
           
        // If credentials are correct, proceed to load the main screen
        else {
            lgUsernamError.setText(""); // Clear any previous error messages
            lgPasswordError.setText(""); // Clear any previous error messages

            loadScreen("MainScreen"); // Load the main screen
        }
    }//GEN-LAST:event_lgbuttonActionPerformed

    private void mnSizetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSizetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnSizetxtActionPerformed

    private void mnFormattxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFormattxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnFormattxtActionPerformed

    private void mnContacttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnContacttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnContacttxtActionPerformed

    private void mnDatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnDatetxtActionPerformed

    private void mnIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnIDtxtActionPerformed
    private boolean validateField(JTextField textField, JLabel errorLbl, String errorMsg, Color errorColor, Color successColor, boolean isValidFormat) {
    if (validationUtil.isNullOrEmpty(textField.getText())) {
        textField.setBorder(createNormalBorder(errorColor));  // Changed to use createNormalBorder
        errorLbl.setText("Field cannot be empty!");
        errorLbl.setVisible(true);
        return false;
    } else if (!isValidFormat) {
        //textField.setBorder(createTitledBorder(errorColor, fieldName)); // Removed the titled border line
        textField.setBorder(createNormalBorder(errorColor));  // Changed to use createNormalBorder
        errorLbl.setText(errorMsg);
        errorLbl.setVisible(true);
        return false;
    } else {
        textField.setBorder(createNormalBorder(successColor));  // Changed to use createNormalBorder
        errorLbl.setVisible(false);
        return true;
    }
}

    
//        private javax.swing.border.TitledBorder createTitledBorder(Color color, String title) {
//        return javax.swing.BorderFactory.createTitledBorder(
//                javax.swing.BorderFactory.createLineBorder(color, 2),
//                title,
//                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
//                javax.swing.border.TitledBorder.DEFAULT_POSITION,
//                new java.awt.Font("Segoe UI", 1, 12),
//                color
//        );
//    }
    private javax.swing.border.Border createNormalBorder(Color color) {
    return javax.swing.BorderFactory.createLineBorder(color, 2);
    }

    private void showDialogBox(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }


    private void mnAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddButtonActionPerformed
    // TODO add your handling code here:
    boolean hasError = true;

    // Validate Name
    hasError &= validateField(
            mnNametxt, nameError, "must be in alphabets.",
            errorColor, yellowColor, validationUtil.ValidName(mnNametxt.getText())
    );
    // Validate ID
    hasError &= validateField(
            mnIDtxt,  idError, "must be 4 digits.",
            errorColor, yellowColor, validationUtil.isValidId(mnIDtxt.getText())
    );
    // Validate Date
    hasError &= validateField(
            mnDatetxt,  dateError, "Enter the correct format.",
            errorColor, yellowColor, validationUtil.isValidDate(mnDatetxt.getText())
    );
    // Validate contact
    hasError &= validateField(
            mnContacttxt,  contactError, "Must start from 98 and be 10 digits.",
            errorColor, yellowColor, validationUtil.ValidContact(mnContacttxt.getText())
    );
    // Validate price
    hasError &= validateField(
            mnPricetxt,  priceError, "must be in digits.",
            errorColor, yellowColor, validationUtil.ValidPrice(mnPricetxt.getText())
    );
    // Validate address
    hasError &= validateField(
            mnStudioAddresstxt,  addressError, "must be in alphabets.",
            errorColor, yellowColor, validationUtil.ValidAddress(mnStudioAddresstxt.getText())
    );
    // Validate size
    hasError &= validateField(
            mnSizetxt,  sizeError, "must be in height X width form.",
            errorColor, yellowColor, validationUtil.ValidSize(mnSizetxt.getText())
    );

    // If no errors, collect data for adding to table
    if (hasError) {
        // Prepare data for the table
        // Retrieve values from combo boxes
        // Use these values in your logic
        paintingInfo items = new paintingInfo(
            Integer.parseInt(mnIDtxt.getText().trim()),
            mnNametxt.getText().trim(),
            mnDatetxt.getText().trim(),
            mnMeduimtxt.getSelectedItem().toString().trim(),
            mnContacttxt.getText().trim(),
            Integer.parseInt(mnPricetxt.getText().trim()),
            mnStudioAddresstxt.getText().trim(),
            mnFormattxt.getSelectedItem().toString().trim(),
            mnSizetxt.getText().trim()
        );

        if (checkDuplicateStudent(items)) {
            // Add the student if no duplicate is found
            mnIDtxt.setBorder(createNormalBorder(errorColor));  // Changed to use createNormalBorder
            idError.setText("Duplicate ID");
        } else {
            artItemList.add(items);
            loadListToTable(artItemList);
            mnIDtxt.setBorder(createNormalBorder(greenColor));  // Changed to use createNormalBorder
            mnNametxt.setText("");
            mnIDtxt.setText("");
            mnDatetxt.setText("");
            mnContacttxt.setText("");
            mnPricetxt.setText("");
            mnStudioAddresstxt.setText("");
            mnSizetxt.setText("");
            mnMeduimtxt.setSelectedIndex(0);
            mnFormattxt.setSelectedIndex(0);
            showDialogBox("Art Item added.", "task successful", JOptionPane.INFORMATION_MESSAGE);
        }
    }    


    }//GEN-LAST:event_mnAddButtonActionPerformed
    private void loadListToTable(List<paintingInfo> itemsList) {
        DefaultTableModel model = (DefaultTableModel) mntable.getModel();

        // Clear existing rows if needed
        model.setRowCount(0);

        // Populate the table with student data
        itemsList.forEach(item -> model.addRow(new Object[]{
              item.getArtId(), item.getName(), item.getDate(), item.getMedium(), item.getContact(), item.getPrice()
              , item.getSize(), item.getFormatt(), item.getAddress()
        }));
    }
    
    private boolean checkDuplicateStudent(paintingInfo item) {
        return artItemList.stream()
                .anyMatch(existingArtItem
                        -> existingArtItem.getArtId() == item.getArtId());
    }

    private void mnNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnNametxtActionPerformed

    private void mnUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUpdateButtonActionPerformed
        
            // TODO add your handling code here:
        boolean hasError = true;

        // Validate Name
        hasError &= validateField(
                mnNametxt, nameError, "must be in alphabets.",
                errorColor, yellowColor, validationUtil.ValidName(mnNametxt.getText())
        );
        // Validate ID
        hasError &= validateField(
                mnIDtxt,  idError, "must be 4 digits.",
                errorColor, yellowColor, validationUtil.isValidId(mnIDtxt.getText())
        );
        // Validate Date
        hasError &= validateField(
                mnDatetxt,  dateError, "Enter the correct format.",
                errorColor, yellowColor, validationUtil.isValidDate(mnDatetxt.getText())
        );
        // Validate contact
        hasError &= validateField(
                mnContacttxt,  contactError, "Must start from 98 and be 10 digits.",
                errorColor, yellowColor, validationUtil.ValidContact(mnContacttxt.getText())
        );
        // Validate price
        hasError &= validateField(
                mnPricetxt,  priceError, "must be in digits.",
                errorColor, yellowColor, validationUtil.ValidPrice(mnPricetxt.getText())
        );
        // Validate address
        hasError &= validateField(
                mnStudioAddresstxt,  addressError, "must be in alphabets.",
                errorColor, yellowColor, validationUtil.ValidAddress(mnStudioAddresstxt.getText())
        );
        // Validate size
        hasError &= validateField(
                mnSizetxt,  sizeError, "must be in height X width form.",
                errorColor, yellowColor, validationUtil.ValidSize(mnSizetxt.getText())
        );
        // add to table is no errors
        if(hasError){
            paintingInfo updatedItem = new paintingInfo(
            Integer.parseInt(mnIDtxt.getText().trim()), // Updated ID
            mnNametxt.getText().trim(),                 // Updated Name
            mnDatetxt.getText().trim(),                 // Updated Date
            mnMeduimtxt.getSelectedItem().toString().trim(), // Updated Medium
            mnContacttxt.getText().trim(),              // Updated Contact
            Integer.parseInt(mnPricetxt.getText().trim()), // Updated Price
            mnStudioAddresstxt.getText().trim(),       // Updated Address
            mnFormattxt.getSelectedItem().toString().trim(), // Updated Format
            mnSizetxt.getText().trim()                 // Updated Size
        );

//        // Try to find and update the existing item in the list
//        boolean isUpdated = artItemList.stream()
//            .filter(existingItem -> existingItem.getArtId() == updatedItem.getArtId()) // Find matching ID
//            .peek(existingItem -> {
//                // Update the item in the list
//                artItemList.set(artItemList.indexOf(existingItem), updatedItem);
//            })
//            .findFirst() // Stop after the first match
//            .isPresent(); // Check if any match was found and updated

        // If the item was updated, show a success message
        if (checkDuplicateStudent(updatedItem)) {
            loadListToTable(artItemList);  // Refresh the table with the updated list
            showDialogBox("Art Item updated.", "Task successful", JOptionPane.INFORMATION_MESSAGE);
            resetFormFields();  // Reset the form fields after successful update
        } else {
            // If no item was updated (ID not found), show an error message
            showDialogBox("Art Item with this ID not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
     }

    }//GEN-LAST:event_mnUpdateButtonActionPerformed

    private void mnDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDeleteButtonActionPerformed
        // TODO add your handling code here:
          // Get the value from the ID text field
    String idText = mnIDtxt.getText().trim();

    // Use the existing method to check if the field is empty
    if (validationUtil.isNullOrEmpty(idText)) {
        validateField(
                mnIDtxt,idError, "enter ID.",
                errorColor, yellowColor, validationUtil.isValidId(idText)
        );
        return; // Exit early if the ID field is empty
    }

    try {
        // Parse the ID text to an integer
        int idToDelete = Integer.parseInt(idText);

        // Check if any item matches the ID and remove it
        boolean isDeleted = artItemList.removeIf(item -> item.getArtId() == idToDelete);

        if (isDeleted) {
            // Reload the table with updated data
            loadListToTable(artItemList);
            JOptionPane.showMessageDialog(this, "Item deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "ID not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid ID. Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_mnDeleteButtonActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        resetFormFields();
    }//GEN-LAST:event_clearActionPerformed

    private void mnPricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnPricetxtActionPerformed

    private void mnLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutButtonActionPerformed
        // TODO add your handling code here:
        lgusernametxt.setText("");
        lgpasswordtxt.setText("");
        loadScreen("LoginScreen"); // Load the main screen
    }//GEN-LAST:event_mnLogoutButtonActionPerformed

    private void mnStudioAddresstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnStudioAddresstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnStudioAddresstxtActionPerformed
    
    private void resetFormFields() {
    // Reset the form fields after successful update
    mnNametxt.setText("");
    mnIDtxt.setText("");
    mnDatetxt.setText("");
    mnContacttxt.setText("");
    mnPricetxt.setText("");
    mnStudioAddresstxt.setText("");
    mnSizetxt.setText("");
    mnMeduimtxt.setSelectedIndex(0);
    mnFormattxt.setSelectedIndex(0);
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AGM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AGM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AGM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AGM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AGM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressError;
    private javax.swing.JButton clear;
    private javax.swing.JLabel contactError;
    private javax.swing.JLabel dateError;
    private javax.swing.JLabel idError;
    private javax.swing.JLabel imgLS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lgImg;
    private javax.swing.JLabel lgPassword;
    private javax.swing.JLabel lgPasswordError;
    private javax.swing.JLabel lgUsernamError;
    private javax.swing.JLabel lgUsername;
    private javax.swing.JButton lgbutton;
    private javax.swing.JPasswordField lgpasswordtxt;
    private javax.swing.JTextField lgusernametxt;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mnAboutus;
    private javax.swing.JButton mnAddButton;
    private javax.swing.JTextField mnContacttxt;
    private javax.swing.JTextField mnDatetxt;
    private javax.swing.JButton mnDeleteButton;
    private javax.swing.JComboBox<String> mnFormattxt;
    private javax.swing.JPanel mnGallery;
    private javax.swing.JLabel mnHimg;
    private javax.swing.JPanel mnHome;
    private javax.swing.JTextField mnIDtxt;
    private javax.swing.JButton mnLogoutButton;
    private javax.swing.JComboBox<String> mnMeduimtxt;
    private javax.swing.JTextField mnNametxt;
    private javax.swing.JPanel mnPanel;
    private javax.swing.JTextField mnPricetxt;
    private javax.swing.JTextField mnSizetxt;
    private javax.swing.JTextField mnStudioAddresstxt;
    private javax.swing.JButton mnUpdateButton;
    private javax.swing.JPanel mnaadmin;
    private javax.swing.JTable mntable;
    private javax.swing.JLabel nameError;
    private javax.swing.JPanel pnLoaddingscreen;
    private javax.swing.JLabel priceError;
    private javax.swing.JProgressBar scLoaddingscreen;
    private javax.swing.JLabel sizeError;
    // End of variables declaration//GEN-END:variables
}
